# Generated by Django 2.2.7 on 2019-12-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
