# Generated by Django 2.2.7 on 2019-12-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapi', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
